spring.application.name=backend
# --- OMDb API ---
omdb.api.base-url=http://www.omdbapi.com
omdb.api.key=${OMDB_API_KEY}
# --- Mongo DB URL ---
spring.mongodb.uri=${MONGO_DB_URI}
# --- OAuth ---
spring.security.oauth2.client.registration.github.client-id=${CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=none
